### ISSUE TITLE
Ensure spaces are valid before using them

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#123]
## Context
Per https://github.com/Ralith/openxrs/pull/101/commits/f82f169e005cebf49b56dce4ac32dd1129dd5dae, we need to ensure we're checking to see whether the spaces we've located are valid before using them.

## TODO
- [x] Add `space_is_valid` helper
- [x] Add to `Hands`
- [x] Add to `Pointers`
- [x] Add to `Sabers`
- [ ] Add to `Camera`

**Comment by kanerogers** [comment]
Whoops, forgot the headset location too.
