### ISSUE TITLE
Finish Beat Saber example

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#130]
## Background
So, here we are.

Now that Hotham 0.1 is _feature complete_ 😱 , it's time to actually do something with it.

All the pieces are here, now we just have to glue 'em together.

## TODO
- [x] Draw up a state machine for the game
- [x] Implement the state machine
- [x] Make it work on the headset

**Comment by kanerogers** [comment]
![IMG_0223](https://user-images.githubusercontent.com/2022375/150473823-1afa9e47-2400-49c7-8f5f-d34a6b232311.jpg)
