### ISSUE TITLE
Fix model loading

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#14]
## Description
It's currently taking forever to load a model, and texture paths are completely hard coded.

## TODO
- [ ] Figure out if it's because of running in release mode
- [ ] Look at using KTX textures
- [ ] Encapsulate all model data in a single struct
