### ISSUE TITLE
Refactor schedule_function functionality into associated resources

### ISSUE THREAD

**Issue by davidkuhta** [leetvr/hotham#149]
## TODO
- [X] apply_haptic_feedback.rs
- [X] begin_frame.rs
- [X] end_frame.rs
- [X] begin_pbr_renderpass.rs 
- [X] end_pbr_renderpass.rs
- [X] physics_step.rs
- [ ] sync_debug_server.rs
- [ ] mod.rs

Refactoring ideas:
1. `apply_haptic_feedback` potentially in `HapticContext` resource.
2. `begin_frame` and `end_frame` can likely be pulled into `XrContext` resource.
3. 'begin_pbr_renderpass` and `end_pbr_renderpass` into `RenderContext` resource.
4. `physics_step` into `PhysicsContext` resource.

**Comment by kanerogers** [comment]
Thanks so much for tackling this @davidkuhta - I think the issues you've highlighted here are all totally real, and there's so much room for improvement in the API.

As per our conversation today I'm going to push back on a refactor of the public API for now. I think I'd like to leave the API very explicit and lowlevel, and let changes be guided by feedback that arises from actually making games. I'm 90% sure that the next iteration of the API is going to look very similar to what you've proposed, but for `0.2` I think I'd like to leave the API as is and focus on cleaning up some of the internals.
