### ISSUE TITLE
Moves run scripts into new scripts directory

### ISSUE THREAD

**Issue by davidkuhta** [leetvr/hotham#153]
## Description
Description goes here! Include why this might be helpful

## TODO
- [X] Move run_on_device.* to crab-saber/examples/scripts/
- [X] Modify scripts to function in new directory 
- [X] Confirm shell script functionality in Unix systems
- [ ] Confirm PowerShell script for Windows
- [ ] Update readme docs and Wiki
