### ISSUE TITLE
Implement simple scene system

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#18]
## Description
Rendering a single asteroid is fun! You know what's better than a single asteroid?

Multiple.. things!

## TODO
- [x] Add `Model`
- [x] Add `SceneObject`
- [x] Implement `load_models`
- [x] Add normal_map to descriptor_layout
- [x] Have `Program::init()` return `Vec<SceneObject>`
- [x] Return multiple `scene_object`s
- [x] Fetch Matrix from gltf
- [x] Add `scene_objects` to `App`
- [x] Modify `Renderer` to have `push_constants`
- [x] Rename shaders to `model.*`
- [x] Load shaders inside `hotham`
- [x] Have shaders read `push_constant` for matrix
- [x] Have shaders read normal
- [x] Have shaders read from normal map
- [x] Pass `scene_objects` to `Renderer::draw()`
- [x] Loop through each `scene_object` in `prepare_frame`
  - [x] Update push constant
  - [x] Bind `descriptor_set`, `index_buffer` and `vertex_buffer` from `scene_object`
- [x] Create Android images 
- [x] Load models from Asset Manager
- [x] Verify working on Android
