### ISSUE TITLE
[Feature] Rendering engine v2

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#202]
## Background
At present, our rendering engine renders things. Great, wonderful,  _marvellous_. BUT:

- We're currently limited to 32 objects on screen
- We use buffers in an extremely inefficient way
- There are no shadows
- We do not know the performance characteristics (waiting on #85)

This is all pretty understandable given Hotham was written by a pretty inexperienced Vulkan developer (cough: @kanerogers), so now it's time.

## TODO
- [x] Research modern rendering techniques (eg. "bindless", DrawIndirect, etc.)
- [x] Benchmark the current renderer #85 
- [x] Identify a new design
- [ ] Implement
  - [x] Investigate current `VulkanContext` / `RenderContext` split
  - [x] Enable necessary physical features
  - [x] Upgrade RenderContext
    - [x]  Change descriptor indexes
    - [x] Create shared VertexBuffer, IndexBuffer, etc.
  - [x] Upgrade gltf_importer (first pass)
    - [x] Migrate Mesh, Material and Texture
  - [x] Modify rendering system (first pass)
    - [x] Bind descriptor sets
    - [x] Push constant for globals
    - [x] Vertex shader
    - [x] Fragment shader
  - [x] **CHECKPOINT**: PBR render passes correctly 
  - [x] **CHECKPOINT**: Stress test runs on device
  - [x] Handle skins, animations 
  - [x] Switch to MultiDrawIndirect
  - [x] Implement GPU culling 

## Next steps
- #209

**Comment by kanerogers** [comment]
Closed in #235
