### ISSUE TITLE
[SYSTEMS] Add simple animation system

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#22]
## Description
It's kind of cool when things move in games, doesn't it?

## TODO
- [x] Initial research
- [x] Add `animation.rs`
- [x] Write test to load `Animation`, with channel etc.
- [x] Implement that shit!
- [x] Rewrite `Model` to use `Node`s
- [x] Implement `Skin` etc.
- [x] Update animation in frame
- [x] Update `Vertex`
- [x] Update `model.vert`
