### ISSUE TITLE
[Maintenance] Cleanup, restructure and refactor - part 1

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#227]
## Description
Now that things are mostly working in Hotham, it's time to clean things up!

## TODO
- [x] Move `World` into `Engine`
- [x] Have all internal systems just take `Engine`
- [x] Get rid of prepared queries
- [x] Update existing examples
- [x] Remove `debug_server` and `debug_frontend`
- [x] Rename all `resources` to `contexts`
- [x] Move all "schedule_functions" into `systems`

## Next
- [ ] #366
- [ ] #367

**Comment by kanerogers** [comment]
Here's my initial thoughts on an API for simple games.

```rust
let app = App::builder().add_system(game_system);
app.run();
```

Where `game_system` is something like:

```rust
pub fn game_system(engine: &mut Engine, game_state: &mut GameState) {
  // do the thing
}
```

Your system will get called after input has been collected and the physics simulation has run, but before rendering occurs.
