### ISSUE TITLE
[Rendering] Add IBL back

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#255]
## Background
Now that we've got some more texture bandwidth to play with, let's add some sweet looking IBLs.

## TODO
- [x] Add back fragment shader code
- [x] Wire up descriptors
- [x] Load static IBL assets

## Further reading
- https://github.com/KhronosGroup/3DC-Certification/tree/main/documents

**Comment by kanerogers** [comment]
Current update: Loading cubemaps is annoying.

**Comment by kanerogers** [comment]
Bad:

![image](https://user-images.githubusercontent.com/2022375/183657309-6809cf41-39c7-42b3-b8ad-c3b522eda8bd.png)

Good (but technically wrong):

![Uploading image.png…]()
