### ISSUE TITLE
[Feature] Add support for environment maps / skyboxes

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#256]
## Background
Skyboxes. We gotta have 'em.

## TODO
- [ ] Add relevant samplers
- [ ] Load files in
- [ ] Wire up fragment shader
