### ISSUE TITLE
[Rendering] Rendering optimisations v2

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#259]
## Background
After getting significant gains in #226, there's still much more juice we can squeeze out of the renderer.

The name of the game is _bandwidth_. We **must** ensure that we pull as little data down as possible in each draw.

## TODO
- [ ] #357
- [x] Use instancing (Qualcomm recommends this: https://developer.qualcomm.com/sites/default/files/docs/adreno-gpu/developer-guide/gpu/best_practices_vertex.html#consider-geometry-instancing)
- [ ] #356
- [ ] #274 
- [ ] https://www.unrealengine.com/en-US/blog/physically-based-shading-on-mobile
- [ ] https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_transform/README.md
