### ISSUE TITLE
The player transitions into deploy mode

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#27]
## Description
The player is aware that now they need to *do* something. Deploy their mechs and defend against aliens.

## TODO
- [ ] Clean up the scene so it's more clear what's going on
- [ ] Write copy explaining to the player what needs to happen
- [ ] Have the audio play in the headset
- [ ] Implement some kind of state machine to move into the right state (eg. so we aren't endlessly looping) (depends on #40)
