### ISSUE TITLE
[Renderer] Switch to instanced, direct draws

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#284]
## Background
Hat in hand, I must concede defeat and accept that `drawIndirect` on the Adreno GPU is cursed. Evil, and broken. I've heard the same from other developers, Oculus employees and there are [various sources](https://developer.qualcomm.com/forum/qdn-forums/software/adreno-gpu-sdk/68152) citing terrible performance. Sigh.

The fix, instead, is to use instanced rendering. Instanced rendering will let us render duplicated geometry *very* quickly. This seems to be another one of those quirks on mobile; while instancing is falling out of fashion on desktops, it's still a HUGE win on mobile devices. Whether that's because there's some hardware fast path (eg. instancing is optimised) or indirect calls are implemented in a garbage way (eg. indirect is unoptimized), we'll never know. 

## TODO
- [x] Ensure instancing actually works (build benchmark suite)
- [x] Design new buffer model
- [ ] Implement culling with fence / submission
- [ ] Ensure all tests work correctly
