### ISSUE TITLE
Indicate to the player that they need to put their mech onto the asteroid

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#29]
## Description
The player needs to know what they need to do next. Otherwise, how will they do it?

## TODO
- [ ] Write and record copy and play with script (depends on #40)
- [ ] Get a mech model
- [ ] Get a "mech carrier" model
- [ ] Have the carrier appear onscreen
