### ISSUE TITLE
[Rendering] Implement support for glTF lighting

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#314]
## Background
glTF implements the usual suspects of realtime dynamic lighting. Let's allow users to import them into their scenes.

## References
- [KHR_lights_punctual](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md)
- [Khronos glTF Sample Viewer](https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/78e6453306923f1c0df3220d45a2e0656b80c326/source/Renderer/shaders/pbr.frag#L179)
- [gltf-viewer-rs](https://github.com/adrien-ben/gltf-viewer-rs/blob/master/crates/viewer/shaders/model.frag)

## TODO
- [x] Implement a hardcoded point light
- [x] Implement a hardcoded spotlight
- [x] #324 
- [x] Add 4 point light members to `SceneParams`
- [x] Fix normals on hands
- [x] Fix IBL

**Comment by kanerogers** [comment]
Hardcoded lights working well; after some refactoring to separate analytical light from IBL, adding the different intensity functions for various lights is pretty trivial. Next step is to add an interface to add lights from the CPU, then after that we can extract them from a glTF file.

**Comment by kanerogers** [comment]
It looks like we're definitely not handling normals correctly. This is how the Normal Tangent Mirror test should look with a single point light in the middle of the scene:

![Normals Good](https://user-images.githubusercontent.com/2022375/184250612-3a52bbc4-47e4-4bfb-b9b0-081528dbd8eb.png)

..and this is how it looks in Hotham:
![Normals Bad](https://user-images.githubusercontent.com/2022375/184250711-f89158e6-bc8a-434c-be0c-a5ccd5c75a0d.png)

**Comment by kanerogers** [comment]
Closed in #327
