### ISSUE TITLE
Implement ECS

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#35]
## Description
We're now starting to have a large number of actors within our system. We need an efficient way of organising them.

## TODO
- [x] Research ECS
- [x] Research Rust ECS libraries
- [x] Pick one
- [x] #41

**Comment by kanerogers** [comment]
## Notes
- Watched this brilliant [GDC talk](https://www.youtube.com/watch?v=W3aieHjyNvw&t=1764s) by a Blizzard developer discussing how ECS is implemented in Overwatch.
- Read [this chapter](http://gameprogrammingpatterns.com/component.html) in Game Programming Patterns about component systems


## Summary
ECS is just another way of organising state and behaviour, just like OOP. Where it differs from OOP is that it *separates* state from behaviour rather than coupling them. 

- A `World` contains `System`s and `Entity`s
- A `Entity` is a collection of `Component`s
- A `Component` **only contains state** -- **no** behaviour.
- A `System` **only contains behaviour** -- **no** state.
- A `System` applies a function to a set of `Component`s and modifies their state.

**Comment by kanerogers** [comment]
## Evaluating Rust ECS Libraries:
- [ ] [hecs](https://github.com/Ralith/hecs)
- [ ] [bevy](https://github.com/bevyengine/bevy)
- [ ] [legion](https://github.com/amethyst/legion)
- [ ] [specs](https://github.com/amethyst/specs)

**Comment by kanerogers** [comment]
## Test implementation
After my exhaustive analysis of the options, I'll try out [legion](https://github.com/amethyst/legion).
