### ISSUE TITLE
[Feature] Easy importing of colliders from glTF files

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#351]
## Background
One of the most time consuming tasks when working on Hotham games is configuring collider geometry. This issue is a first past attempt at resolving that problem.

## TODO
- [ ] When importing meshes, check for `_HOTHAM_COLLIDER_WALL` or `_HOTHAM_COLLIDER_SENSOR` suffixes
- [ ] For `WALL` meshes, create a collider and attach it to the corresponding entity
- [ ] For `SENSOR` meshes, create a collider and mark it as a sensor
