### ISSUE TITLE
[Simulator] Remove existing simulator and transition to editor

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#428]
## Background
The current simulator has a number of different problems:

- #204 
- #418 
- It's big, ugly and complicated

Instead, the work in #419 has shown that splitting the simulator into its own process is cleaner, simpler and more correct.

## TODO
- [ ] [Editor] Add Linux support
- [ ] [Editor] Add macOS support
- [ ] [Editor] Gracefully handle window closing
