### ISSUE TITLE
Render Asteroid and Refinery with `legion` architecture

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#50]
## Overview
Now that we've successfully ported most of our code to `legion`, it's time to integrate everything.

For our first pass, we'll just try rendering the Asteroid and the refinery.

## TODO
- [x] Modify `App` to run the `legion` schedule.
- [x] Modify `Renderer` accordingly
- [x] Bind to SceneData
- [x] Modify `hotham-asteroid` to return the asteroid and the refinery parented to it

**Comment by kanerogers** [comment]
At the part where I was afraid things would go wrong.. and they are. 😆 

In order to import a model into the game world, we create a world for each model, then try to use `world.clone_from` to copy from the **model** world into the **game** world. Not working for some reason..

**Comment by kanerogers** [comment]
Problem was I needed to tell the merger how to copy things. That's a bit irritating, but oh well:

    merger.register_copy::<Transform>();
    merger.register_copy::<Mesh>();
    merger.register_copy::<TransformMatrix>();
    merger.register_clone::<Skin>();
    merger.register_copy::<Joint>();
    merger.register_copy::<Parent>();
