### ISSUE TITLE
The player receives instructions on what to do next

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#6]
## Description
We know what the point of this game is, but the user is probably completely in the dark. Having some audio to tell the user what's going to happen is super useful.

## TODO
- [x] Get some cool synthesised speech
- [x] Have it play in the headset 
- [x] Sound working on Android
- [x] Sound only plays 5 seconds into game load
