### ISSUE TITLE
0.1 release roadmap

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#64]
## Intro
After a bunch of work, `hotham` is *dangerously* close to being ready for other human beings to use. 

Here's a list of things that need to be done first.

### Code stuff 💻 
- [x] #65
- [x] #54 
- [x] #46 
- [x] #83
- [x] #40 
- [x] #52 
- [ ]  #59 
- [ ] #55 
- [ ] #42 
- [x] #44 
- [x] #66
- [x] #67
- [x] #84
- [ ] #85

### Examples
- [x] #75
- [x] #69
- [ ] #68
- [ ] #70

### Evil Marketing stuff :skull:
- [ ] Website
- [ ] FAQ
- [ ] Book (4-5 pages explaining what Hotham is, how it works, with diagrams)
- [ ] "Beat Saber" clone tutorial - step by step with video
- [ ] "3 minute Launch" video (who I am, what Hotham is, what it's trying to do, etc.)

### Repo stuff :construction:
- [x] #62 
- [x] #71
- [x] #72
- [x] #73
- [x] #74
- [x] #76
- [x] #79
- [ ] Upload to `crates.io`
- [ ] Verify `docs.rs` works
- [ ] Make sure sponsor stuff is working 🤑

**Comment by kanerogers** [comment]
Hey, @wbrickner  @ralith @pwc any suggestions? 😄
