### ISSUE TITLE
"Good enough" glTF PBR support

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#65]
## Background
Currently things in hotham look terrible. Let's fix that!

## Research
- [x] Real-Time Rendering, Fourth Edition
- [x] [Sascha's Implementation](https://github.com/SaschaWillems/Vulkan-glTF-PBR)
- [x] [Real Shading in Unreal](https://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf)
- [x] [Substance's PBR guide](https://substance3d.adobe.com/tutorials/courses/the-pbr-guide-part-1)
- [x] [LearnOpenGL - PBR](https://learnopengl.com/PBR/Theory)
- [x] [Moving Frostbite to PBR](https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf)

## TODO
- [x] Write an integration test for `rendering_system` that takes a path to a gltf file and outputs the render to a file
- [x] Import @SaschaWillems PBR shaders

## RenderContext
- [x] Update descriptor sets
  - [x] Update SceneSet
  - [x] Update MeshSet
  - [x] Add MaterialSet
- [x] Add `Material` struct
- [x] Update `PushConsts` 
- [x] Update `Pipeline` 
- [x] Add `SceneParams` 
- [x] Update scene UBO -> can we stick with push constants for vertex shader?
- [x] Investigate handling of non-skinned entities

## Mesh
- [x] Add `Vec<Primitive>`
- [x] Push `VertexBuffer` and `IndexBuffer` into `Primitive`
- [x] Add `Material` to `Primitive`
- [x] Add all material bindings
- [x] Add `texture_descriptor_set` to `Primitive`

## renderer_system
- [x] Bind to correct descriptor sets
- [x] Multiview

## gltf_importer
- [x] Update `Vertex`
- [x] Import correct Vertex attributes
- [x] Import correct images
- [x] Create `Material`

## Test models
- [x] [Broken helmet](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DamagedHelmet) model correctly
- [x] [Sponza](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza) correctly
- [x] [THE GLORIOUS MCRN DONAGER](https://sketchfab.com/3d-models/mcrn-donnager-the-expanse-05e9f9006d914fcd96e95fbd452aaa28) correctly

**Comment by kanerogers** [comment]
@ralith any tips based on your experience with Vulkan/PBR?

**Comment by Ralith** [comment]
Seems like a good plan to me! I've been warned that LearnOpenGL's BRDF is slightly wrong but I'm far from an expert on those.

**Comment by kanerogers** [comment]
> Seems like a good plan to me! I've been warned that LearnOpenGL's BRDF is slightly wrong but I'm far from an expert on those.

Honestly whenever I read the words "OpenGL" my eyes narrow, but I'll make sure to take it with a couple extra grains of salt. 😄

**Comment by kanerogers** [comment]
![render](https://user-images.githubusercontent.com/2022375/132160605-58e80520-e20a-4a70-9109-723e03fec27a.jpeg)

Work in progress. Feels like there's still a couple things I need to add.. 😆

**Comment by kanerogers** [comment]
Rather than re-invent the wheel again, I will simply use @saschewilliems shaders as a base, and then adapt the code around them, updating to our specific needs.

**Comment by kanerogers** [comment]
We can probably skip `IBLContribution` for now, it's a nice to have but there's a big on-ramp in getting it going.

**Comment by kanerogers** [comment]
We're getting there! Here's the current WIP:

![render](https://user-images.githubusercontent.com/2022375/132610570-04fcdd38-7f4e-4450-96fe-3a46ccc1940d.jpeg)

Looks like there's a couple of problems:

- Scene is too dark
  - Potentially something to do with `scene_params` not being pushed properly?
  - IDEA: Try hardcoding params in shader, experimenting with renderdoc
 - Helmet is rotated incorrectly
   - I spent a couple hours last night fiddling around with orientation and once again I'm getting confused between Vulkan's coordinate system. Since we're a Vulkan only renderer, we should be consistently using Vulkan coordinates (-Y is up) but I worry that there's "correction" code somewhere in the pipeline that past me wrote and forgot about.
    - Another gotcha is the difference between `nalgebra`'s `Quaternion` constructor (w, x, y, z) and `gltf`'s storage order (x, y, z, w). Have added more tests to `gltf_importer`
    - Should we also be correcting imported vertices? eg. `y = y *1` on import? More experimentation required.

**Comment by kanerogers** [comment]
![render](https://user-images.githubusercontent.com/2022375/132785845-a3f46bc7-e526-403c-97aa-288210ef3e6d.jpeg)

Getting there:
- [ ] Our screenshot was not correctly converting from linear sRGB to non-linear sRGB. Fixed that with the handy `palette` crate.
- [ ] Applied the `fov` from the Quest 1 headset just so our reference is looking a bit better.

Remaining problems:
- [ ] Helmet is upside down.
  - [ ] It's definitely something to do with the Y axis. No matter what rotation I give the helmet, it appears upside down (that is, something that should be at the top of the screen is at the bottom)
  - [ ] I'll look more closely over the different `gltf `-> Vulkan implementations and see if I can find anything amiss.
- [ ] Scene not rendered correctly 
  - [ ] Scene is still too dark
  - [ ] Helmet visor appears missing

**Comment by kanerogers** [comment]
```glsl
locPos.y = -locPos.y;
```

Whelp, that'll do it. 😆

**Comment by kanerogers** [comment]
![render](https://user-images.githubusercontent.com/2022375/132832069-25c828be-cf1f-49f4-8c25-ff403e3d1a32.jpeg)
Looking nice! 😄 

- Had a huge number of issues with colour spaces. Huge thanks to @Ralith as always for helping me understand 1% of colour.. stuff.
- @SaschaWilliems's examples *manually* convert the texture images to colour space in the shader. I guess his goal is "drag and drop" compatibility with glTF files.
- Our asset import system really needs some improvement. We *must* come up with a way to easily convert textures to `.ktx2` *properly*.

Haven't tested on headset yet, I'm sure there's a whole bunch of issues, but I think this is a great place to leave it for tonight! 😄

**Comment by Ralith** [comment]
> I guess his goal is "drag and drop" compatibility with glTF files.

That doesn't make a lot of sense, FWIW; that conversion can be automated on both ends through use of proper texture formats.

**Comment by kanerogers** [comment]
Checked on headset, looking *great*! Noticed a bug where reflections aren't working correctly in the right eye, will take a look now.

**Comment by kanerogers** [comment]
Having issues getting RenderDoc to work on the headset:

**Comment by kanerogers** [comment]
Looks to have been an issue with the Quest 1. Using the Quest 2 for now, but will be nice to get Renderdoc working again.

Today's bugs:
- Issue with right eye reflections not working was due to alignment of UBO. 
- Used `ash::utils::Align` when writing to device memory and switched to `vec4` instead of `vec3`  since we've got Matrix4s in our UBO.
- Had issues with hands not working correctly, but was due to some leftover hacks when trying to fix the upside down problems of last week

Tomorrow:
- Sponza, then hopefully we're wrapped up!

**Comment by kanerogers** [comment]
Today's progress:

- Got Sponza to load
- Ensured all textures are in sRGB format
- Hit the limitations of non IBL lighting

Now we'll need to implement IBL properly. Let's see how we go.

**Comment by kanerogers** [comment]
![render Normal](https://user-images.githubusercontent.com/2022375/133708465-bef6d427-d2e9-471c-80b8-1c0c31cd63a1.jpeg)

Got IBL implemented now, looking much better! 😄

**Comment by kanerogers** [comment]
I think we're done with this for now! There's a bunch more things I could add, but I really want them to be driven by the requirements of the examples, not by my "wouldn't it be cool if.." thoughts. 😆
