### ISSUE TITLE
Settle on 0.1 API

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#66]
## Context
#131 resulted in a massive refactoring of so much of Hotham's internal systems. That's meant the previous `App` API we had is now deceased. We now need a rewrite

## TODO
- [ ] Spent a couple hours researching different approaches
- [ ] Pick something
- [ ] Don't fucking bikeshed it
- [ ] Don't shave yaks

**Comment by kanerogers** [comment]
![image](https://user-images.githubusercontent.com/2022375/151651051-3cfa0d35-82a9-41b7-9e88-bc450edb1f7c.png)
Don't do it.

**Comment by kanerogers** [comment]
![image](https://user-images.githubusercontent.com/2022375/151656352-d565ffc5-f407-46c8-9ebe-daf94b8bfd4e.png)
