### ISSUE TITLE
Fix asset importer

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#83]
## Description
`gltf_importer` is kind of janky at the moment. We need to settle on a simple API that.

## TODO
- [x] Create a "known good" `.glb` file
- [x] Write a test to import it
- [x] Make `.glb` the only interface

**Comment by kanerogers** [comment]
Been thinking about this for a little while, here's some random thoughts:

- Asset import is a mission critical system. Even for 0.1, we *have* to have something solid working.
- The simplest thing to do have solid imports of `.glb` files with `.ktx2` images.
- With our *input* well defined, we can then communicate separately, or have tools, around how that input should be generated (eg. in a `build.rs` file, cargo command, etc.)

**Comment by kanerogers** [comment]
Currently blocked on https://github.com/gltf-rs/gltf/issues/303.

**Comment by kanerogers** [comment]
After a bit of investigation, it looks like it's going to be a bit of a hassle to get `gltf-rs` to work with KHR_texture_basisu, so let's just move on.
