### ISSUE TITLE
Basic UI support

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#93]
## Description
This is one of the last "big features" needed before we can ship 0.1.

UIs are big, scary things and I've tried as much as possible to avoid them with a 10 foot pole. But, games without UI are no games at all. VR games, doubly so.

## TODO
- [x] Refactor current functionality
- [x] Add minimal working egui example
- [x] Integrate egui into hotham
- [x] Interactivity

**Comment by kanerogers** [comment]
## Interactivity plan

- [ ] Use "aim" pose to get the start of a ray from the player's controller
- [ ] Render some sort of ray indicator
- [ ] (hand waving) cast a ray to see if it hits a Panel (my UI abstraction) component
- [ ] Render a "dot" on the panel that corresponds with where the ray has hit
- [ ] Have buttons highlight/toggle when cast
- [ ]  Squeeze trigger == press button
- [ ]  ????
- [ ]  Beat Saber
