### ISSUE TITLE
Invert control of app

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#94]
## Background
The first iteration of Hotham was based around the idea that we could provide a nice wrapper around some shaders provided by an artist. *Ha ha ha*.

Jump forward a couple months and now Hotham is trying to be a fully fleshed out game engine for VR. This means that the shape of the AI needs to change dramatically in order to be ergonomic.

## TODO
- [x] Change `app::new()` to pass in `World`, `Resources` and `Schedule`.
- [ ] Provide a `default_resources` function
- [ ] Ensure all `systems` are exported so a user can create their own schedule
- [ ] Update examples
