### ISSUE TITLE
Add features to debugger

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#98]
While working on #69, I've encountered some difficulties in development/debugging. To help make this easier, I'm going to add some extra features to the debugger:

- [ ] Time travelling
- [ ] Visualisation
- [ ] Tree View
- [ ] Inspector

This will likely be pretty tricky.

## TODO
- [x] Sketch out rough prototype
  - [x] Add view panel
  - [x] Add toggles on view panel
  - [x] Display a model from `glb`
  - [x] Display a wireframe
  - [x] Display tree
  - [x] Display inspector
  - [x] Display timeline
- [x] Update hotham side
- [x] Wire up 
- [x] Add physics objects from hotham
